1.0.2: cleaned up circleci yml; updated node_modules;

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,11 +8,11 @@ executors:
 
   playwright-executor:
     docker:
-      - image: mcr.microsoft.com/playwright:v1.56.1-noble
+      - image: mcr.microsoft.com/playwright:v1.57.0-noble
     working_directory: ~/project
 
 commands:
-  install_node_24:
+  install_node:
     steps:
       - run:
           name: install missing dependencies
@@ -22,17 +22,14 @@ commands:
             apt-get clean
             rm -rf /var/lib/apt/lists/*
       - run:
-          name: get nvm version
-          command: |
-            curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r .tag_name > /latest_nvm_version.txt
-      - run:
           name: install nvm
           command: |
-            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$(cat /latest_nvm_version.txt)/install.sh | bash
+            export NVM_VERSION="$(jq -r .engines.nvm package.json)"
+            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
       - run:
           name: install node 24
           command: |
-            export NODE_VERSION=24.11.0
+            export NODE_VERSION="$(jq -r .engines.node package.json)"
             export NVM_DIR="$HOME/.nvm"
             [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
             nvm install $NODE_VERSION
@@ -48,44 +45,21 @@ commands:
           command: |
             set +e
             set +o pipefail
-            echo node:
-            node --version
-            echo
-            echo npm:
-            npm --version
-            echo
-            echo pnpm:
-            pnpm --version
-            echo
-            echo yarn:
-            yarn --version
-            echo
-            echo aws:
-            aws --version
-            echo
-            echo postgres:
-            postgres --version
-            echo
-            echo docker:
-            docker --version
-            echo
-            echo jq
-            jq --version
-            echo
-            echo python3
-            python3 --version
-            echo
-            echo gzip
-            gzip --version
-            echo
-            echo tar
-            tar --version
-            echo
-            echo unzip
-            unzip --version
-            echo
-            echo zip
-            zip --version
+            echo "aws: $(aws --version 2>/dev/null | head -n1 || echo 'not found')"
+            echo "docker: $(docker --version 2>/dev/null | head -n1 || echo 'not found')"
+            echo "gzip: $(gzip --version 2>/dev/null | head -n1 | awk '{print $2}' || echo 'not found')"
+            echo "jq: $(jq --version 2>/dev/null || echo 'not found')"
+            echo "node: $(node --version 2>/dev/null || echo 'not found')"
+            echo "npm: $(npm --version 2>/dev/null || echo 'not found')"
+            echo "nvm: $(nvm --version 2>/dev/null || echo 'not found')"
+            echo "playwright: $(playwright --version 2>/dev/null || echo 'not found')"
+            echo "postgres: $(postgres --version 2>/dev/null | head -n1 || echo 'not found')"
+            echo "pnpm: $(pnpm --version 2>/dev/null || echo 'not installed')"
+            echo "python3: $(python3 --version 2>/dev/null || echo 'not found')"
+            echo "tar: $(tar --version 2>/dev/null | head -n1 | awk '{print $(NF)}' || echo 'not found')"
+            echo "unzip: $(unzip -v 2>/dev/null | head -n1 | awk '{print $2}' || echo 'not found')"
+            echo "yarn: $(yarn --version 2>/dev/null || echo 'not installed')"
+            echo "zip: $(zip -v 2>&1 | grep 'This is Zip' | awk '{print $4}' || echo 'not found')"
             exit 0
 
 jobs:
@@ -94,28 +68,16 @@ jobs:
     steps:
       - checkout:
           method: blobless
-      - install_node_24
+      - install_node
       - output_versions
       - restore_cache:
           keys:
             - website-{{ .Branch }}-test-{{ .BuildNum }}
             - website-{{ .Branch }}-test-
             - website-
-#      - run:
-#          name: install pnpm
-#          command: wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
-#      - run:
-#          name: load pnpm path
-#          command: source /root/.bashrc
-#      - run:
-#          name: pnpm install using lockfile
-#          command: pnpm install --frozen-lockfile
       - run:
           name: npm install using ci
-          command: npm ci
-#      - run:
-#          name: output pnpm-lock.yaml
-#          command: cat pnpm-lock.yaml
+          command: npm ci --no-audit --no-fund
       - run:
           name: output package-lock.json
           command: cat package-lock.json
@@ -127,15 +89,6 @@ jobs:
           command: |
             mkdir -p ~/project/test-reports/eslint
             ~/project/node_modules/eslint/bin/eslint.js -c eslint.config.mjs src/** *.mjs --format junit --output-file ~/project/test-reports/eslint/eslint-src.xml
-#      - run:
-#          name: build testing for vite preview
-#          command: pnpm run build-tests
-#      - run:
-#          name: install playwright default browsers
-#          command: pnpm exec playwright install --with-deps
-#      - run:
-#          name: run playwright tests
-#          command: export CHECK_SCREENSHOTS=TRUE;export CIRCLE_CI=TRUE;pnpm exec playwright test
       - run:
           name: build testing for vite preview
           command: npm run build-tests-ci
@@ -188,8 +141,6 @@ workflows:
                 - hotfix
                 - production
       - deploy:
-          context:
-            - aws-access
           filters:
             branches:
               only:
